export default {
    sendMailNotifications: true,
    playSound: true,
    refreshRate: 10000,
    sendTo: 'example@example.com',
    smtpHost: 'smtp.gmail.com',
    smtpPort: 465,
    urlsToCheck: [
        'https://store.ui.com/collections/early-access/products/dream-router-ea',
        'https://store.ui.com/collections/unifi-protect/products/camera-g4-instant-ea',
        'https://store.ui.com/collections/unifi-protect/products/g4-doorbell-pro-ea',
        'https://store.ui.com/collections/early-access/products/dream-router-ea',
        'https://store.ui.com/collections/early-access/products/g4-doorbell-pro-poe-adapter-ea',
        // 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-ai-360',
        // 'https://store.ui.com/collections/unifi-protect/products/unifi-video-g3-flex-camera',
        // 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g3-instant-camera',
        // 'https://store.ui.com/collections/unifi-protect/products/unifi-video-camera-g3-bullet',
        // 'https://store.ui.com/collections/unifi-protect/products/uvc-g4-dome',
        // 'https://store.ui.com/collections/unifi-network-switching/products/usw-flex',
        // 'https://store.ui.com/collections/unifi-protect/products/uvc-g4-doorbell',
    ],
}